### ISSUE TITLE
incosistent package name from xontrib module

### ISSUE THREAD

**Issue by doronz88** [rpdelaney/xontrib-brace-expansion#1]
Currently, this package is installed and loaded as follows:

```shell
xpip install xontrib-brace-expansion
xpip load expand_braces
```

This is also not reflected correctly in project's documentation and should be refactored to `xpip load brace_expansion`

I could submit this as a PR if you prefer

**Comment by rpdelaney** [comment]
Unless there is a convention for xontribs otherwise, I think I'd prefer the code were refactored to match the documentation, rather than the other way around. I'll be happy to review a PR for this if you get to it before I do.

**Comment by doronz88** [comment]
By refactoring the code to match the documentation so you do agree it should be `xpip load brace_expansion`

**Comment by rpdelaney** [comment]
Yes, exactly
